config/routes.rb
Rails.application.routes.draw do
  devise_for :users

end

app/models/item.rb
class Item < ActiveRecord::Base
    belongs_to :user
    scope :visible_to, -> (user) { user ? all : where(@items.user = @user) }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :items
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  include SessionsHelper
  
  private
    def require_sign_in
      unless current_user
        flash[:alert] = "You must be logged in to do that."
        redirect_to new_session_path
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
  def new
  end
 
  def create

    user = User.find_by(email: params[:session][:email].downcase)

    if user && user.authenticate(params[:session][:password])
      create_session(user)
      flash[:notice] = "Welcome, #{user.name}, let's get going."
      redirect_to root_path
    else
      flash.now[:alert] = 'Invalid email/password combination'
      render :new
    end
  end
 
  def destroy

    destroy_session(current_user)
    flash[:notice] = "You've been signed out, come back soon!"
    redirect_to root_path
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
     @user = User.new
  end
  def create
     @user = User.new
     @user.name = params[:user][:name]
     @user.email = params[:user][:email]
     @user.password = params[:user][:password]
     @user.password_confirmation = params[:user][:password_confirmation]
     
     if @user.save
      flash[:notice] = "Welcome to BlocItOff #{@user.name}!"
      create_session(@user)
      redirect_to root_path
     else
       flash.now[:alert] = "There was an error creating your account. Please try again."
       render :new
     end
  end
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    
    def index
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
    <div class="container">
      <ul class="nav nav-tabs">  
      <li><%= link_to "Home", welcome_index_path %></li>
      <li><%= link_to "Blocitoff", items_path %>></li>
      
  # Needs work below
  
      <li><%= link_to "User", topics_path %></li>
      <li><%= link_to "About", about_path %></li>
      <div class="pull-right user-info">
         <%= link_to "Sign Up", new_user_path %>
         <% if current_user %>
              <%= image_tag current_user.avatar_url(48), class: "gravatar" %>
              <div class="pull-right">
               <%= link_to current_user.name, user_path(current_user) %> <br/> <%= link_to "Sign Out", session_path(current_user), method: :delete %>
              </div>
         <% else %>
           <%= link_to "Sign In", new_session_path %> or
           <%= link_to "Sign Up", new_user_path %>
         <% end %>
      </div>
      </ul>
 
       <div class="flash">
         <% if flash[:notice] %>
           <div class="alert alert-success">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <%= flash[:notice] %>
            </div>
         <% elsif flash.now[:alert] %>
            <div class="alert alert-danger">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <%= flash.now[:alert] %>
            </div>
         <% elsif flash[:alert] %>
            <div class="alert alert-warning">
              <button type="button" class="close" data-dismiss="alert">&times;</button>
              <%= flash[:alert] %>
            </div>
        <% end %>
       </div>
  
    <%= yield %>

    </div>

</body>
</html>

app/views/welcome/index.html.erb
<br>
 <div class="jumbotron">
   <h1>Blocitoff</h1>
   <p>Blocitoff is a self destructing to-do list</p>
   <p>
     <%= link_to "Sign In", new_session_path %> or
     <%= link_to "Sign Up", new_user_path, class: 'btn btn-primary' %> today!
   </p>
 </div>
 
 <div class="row">
   <div class="col-md-4">
     <h2>Will keep you focused on the things that matter</h2>
     <p>This is the only to-do list that you'll ever need</p>
   </div>
   <div class="col-md-4">
     <h2>Super efficient</h2>
     <p>You'll be more succesful if you use blocitoff</p>
   </div>
   <div class="col-md-4">
     <h2>Makes you better looking</h2>
     <p>Studies have shown that using blocitoff will make you better looking</p>
   </div>
 </div>